# FROM python:3.8-slim-buster
FROM --platform=linux/amd64 python:3.8-slim-buster
RUN sleep 60

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]